development:
  adapter: postgresql
  encoding: unicode
  database: kingoflearn_dev
  pool: 5
  host: localhost
  username: wayne
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: kingoflearn_test
  pool: 5
  host: localhost
  username: wayne
  password:
  
production:
  adapter: postgresql
  encoding: unicode
  database: kingoflearn_prod
  pool: 5
  host: localhost
  username: wayne
  password: